####################################################################################
#                                      SPRING                                      #
####################################################################################
spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      naming:
        # snake case -> camel case
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: true
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 100
        # batch insert size
        jdbc:
          batch_size: 1000
  mail:
    host: smtp.gmail.com
    port: 465
    default-encoding: UTF-8
    username: "VALUE"
    password: "VALUE"
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            protocols: TLSv1.2
            enable: true
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  rabbitmq:
    # deserialize 오류 방지
    listener:
      simple:
        message-converter:
          allowed-classes:
            - com.advance.mail.service.dto.MqMailDto
    host: localhost
    port: 5672
    username: guest
    password: guest
####################################################################################
#                                      CUSTOM                                      #
####################################################################################
custom:
  datasource:
    tenancy-ids:
      - "00001"
      - "00002"
      - "00003"
  hikari:
    maximum-pool-size: 5
    minimum-idle: 2
    # ms
    connection-timeout: 30000
    # ms
    idle-timeout: 600000